### ISSUE TITLE
How to ignore status code?

### ISSUE THREAD

**Issue by devnsfw** [stashapp/CommunityScrapers#1338]
I'm trying my hand at writing a new scraper, specifically, for BellesaPlus. This site has a JSON endpoint, so I'm using a JsonScraper (an example URL with a video id would be  https://bellesaplus.co/api/rest/v1/videos/7918)

The problem is, when not authenticated to the site (as the scraper would be), the JSON response has a slightly different wrapper (no problem, I already accounted for it), but also the response has a 402 status code (payment required).

Stash flashes a brief 403 Forbidden error when trying to scrape and finding this.
I tried using CDP but I guess chrome mangles the JSON as it tries to render it, because then I get an invalid JSON file.
Is there a way to tell Stash to ignore the status code (or at least, just 402) and carry on parsing the response anyway?

**Comment by plz12345** [comment]
I know this is late, but better than never.

I think the easiest workaround there is going to be a Python script to execute the API calls, where you can fully control the error handling/suppression.  It is pretty interesting that they throw a HTTP 402 but still give you the content, albeit wrapped in that other bit.  Take a look at the TeamSkeet scraper as an example, since that's also doing JSON API calls.  And thanks for tackling this studio, I'm a fan.  :)

**Comment by devnsfw** [comment]
Does spinning a new python interpreter just to do minimal processing look like a good solution to you? I had arrived at the conclusion that this was doable, but it doesn't feel right to me. If the call can be made from stash, and stash has a good postprocessing engine, I think it is preferable to handle it from within it, just by adding a new directive that tells to ignore the status code.

I could put my money where my mouth is, but I'm not proficient enough with go yet.

**Comment by plz12345** [comment]
Me either, that's why I suggested something that wouldnt require Stashapp code changes.

**Comment by Maista6969** [comment]
This should be raised in the Stash repo, but for now the overhead of Python scrapers does not seem to be significant
