### ISSUE TITLE
VRBangers scraper

### ISSUE THREAD

**Issue by Tanarion40** [stashapp/CommunityScrapers#1466]
Hello, I have a problem with VRBangers scraper 

I receive the message: scraper VRBangers: http error 404:Not Found

Note that all was working well yesterday.

By the way, a big thank you for all your work. It's great :)

**Comment by Maista6969** [comment]
I am unable to reproduce this: the scraper works both when I try to scrape an URL and when I use "Scrape with..."

I think we need some more information here: are you using the latest version of the scraper, the one that says `Last Updated February 27, 2023` at the bottom? How exactly are you using the scraper and what scene are you trying to scrape? 🙂

**Comment by Asuryan34** [comment]
Hello.

Thank you for your answer.
Yes, I have the latest version.
I tried to scrap around 30 VRBANGERS Scenes (From the Scene tab). It succeeded with the 6 first and stoped. When I tried again, I got this message.
I though first that I may have been blocked because of too many queries so I tried to change my VPN server / close my VPD without any success.

Note that I can scape other videos with different scrappers.

**Comment by Maista6969** [comment]
All right, I think I've figured this one out: the way the scraper works in Tagger mode is that it looks at the filename for patterns like `vrbangers_title_of_video_4k_1440p.mp4` and then it will try to scrape from `vrbangers.com/video/title-of-video`

If any of your files are from scenes that have either been removed from the site or have a different title then it will fail with a 404, stopping any further scrapes down the list. What is the filename of the scene that is failing to scrape?

**Comment by Asuryan34** [comment]
Hello.

You were right.  Some words were missing in the title. So, if one title has an error, the scrapper just stop and wont scan the next files. It's why I though it wasn't working anymore *until I fix the title of the first file of the list)

Thank you for your help

**Comment by Maista6969** [comment]
Glad we could figure it out 🙂
