### ISSUE TITLE
ItsPOV Scraper only scrapes tags

### ISSUE THREAD

**Issue by grantgro** [stashapp/CommunityScrapers#1534]
ItsPOV scraper needs updated. I am only getting generic tags to scrape when running it in it's current form

**Comment by Maista6969** [comment]
This entire scraper needs to be rewritten since they no longer have any public information on their subsites, only on itspov.com

The reason you only got tags was because of the change in their URLs: the new URLs at itspov.com no longer match what's found in [ItsPOV.yml](https://github.com/stashapp/CommunityScrapers/blob/cd0d39c19fcb609cf36adb50306372d8178e52d8/scrapers/ItsPOV.yml), but it accidentally matched the scraper for tspov.com (this has been [fixed](https://github.com/stashapp/CommunityScrapers/commit/cd0d39c19fcb609cf36adb50306372d8178e52d8))

I will have time to fix this scraper next week if no one else submits a PR by then. Thank you for reporting this 👍
