### ISSUE TITLE
[Discussion] RealityKingsOL & MindGeek

### ISSUE THREAD

**Issue by Belleyy** [stashapp/CommunityScrapers#181]
I think we need to discuss about these scrapers.

As stated by @bnkai :
> Imo we should keep the 2 separate scrapers and if needed make a 3rd
Verifying/Maintaining a scraper with a huge lists of urls is more difficult than a couple of scrapers with half the urls

I am ok for seperate long list of URL, but i want to know what determine where to put the URL. 
Should we make:
- Main MindGeek scraper with main sites, like Babes, Mofos, Fakehub,.. ?
- Secondary MindGeek with series site like momslickteens, welivetogether, iknowthatgirl,... ?

@budislov made a comment in a previous PR:
> I noticed that the site fakehub.com should be moved from RealityKings/MindGeek to RealityKingsOL.

I would like to know why ?

I think we need to rename the RealityKingsOL too.

**Comment by bnkai** [comment]
@Belleyy i meant keep the site list down when the selectors are not the same. No need to add a lot of unions/complex selectors just  to make all sites work. Obviously if the same or near same selector works for all sites they should be put together.

Fakehub worked for me where it was so  i don't see why it should be moved.

RealitykingsOL (Old Layout) was the simplest i could think of to differentiate from Realitykings. Any recommendation for a new name is welcome as i too think it should be renamed now.

**Comment by budislov** [comment]
@Belleyy you can disregard the comment about fakehub.com being moved to RealityKingsOL. I made the comment before pulling down your latest changes and properly testing.

I have been trying to wrap my head around this whole thing and in my mind I can see things organized in this way: 

MindGeek1.yml - contains sites that have the layout of brazzers.com and realitykings.com (i.e. the current Brazzers.yml)
MindGeek2.yml - this would be the current MindGeek.yml scrapper that has the scene and performer scrapper.
MindGeek3.yml - this would be for sites that do not require the performer scrapper but have the same scene scrapper as MindGeek2.yml.

I believe that any sites currently in RealityKingsOL can be worked into either MindGeek2 or MindGeek3 mentioned above. Also, since RealityKingsOL is the old layout, I would rather see it "retired" in favor of the new layout in the current MindGeek.yml. 

This would also help keep the list of sites per file smaller. Not sure if I am over thinking it, but this seems like a simple enough set of criteria to follow.

**Comment by bnkai** [comment]
Closing. If anyonw want to procede with changes make a new issue or a PR.
