### ISSUE TITLE
theporndb.net - Not Currently Scrapable 

### ISSUE THREAD

**Issue by GronsoBitburg** [stashapp/CommunityScrapers#1856]
**Name of site**

[theporndb.net](https://theporndb.net/)

**URLs that you would expect to scrape**

Example URLs for scenes, performers, movies, galleries

https://theporndb.net/scenes/
https://theporndb.net/movies/
https://theporndb.net/performers/

Any additional notes about this site
Previously this site changed URL but seems that we cannot use URL scraping for currently. This is the best site for scraping data, but it won't work just yet without a change to the community scrapers

**Comment by Maista6969** [comment]
We recommend that you use the stash-box compatible endpoint when scraping from ThePornDB as described in the [guide to scraping](https://docs.stashapp.cc/beginner-guides/guide-to-scraping/#use-theporndb-endpoint) and also mentioned in the [list of tools on ThePornDB itself](https://theporndb.net/tools). Unfortunately, due to the differences in how TPDB and the stash-box software (used by StashDB, PMVStash, FansDB) work this will only let you scrape scenes and performers.

If you'd like to scrape movies or JAV you can use the [ThePornDBMovies](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/ThePornDBMovies.yml) and [ThePornDBJAV](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/ThePornDBJAV.yml) scrapers, both of which can be installed from the Community feed.

Do note that these are among the rare scrapers that will actually need to be modified locally in order to function: find them on your disk, open them with a text editor and scroll to the bottom and see the note on where to add your API key.
