### ISSUE TITLE
Failing to get any .py scraper to work

### ISSUE THREAD

**Issue by seeshepard** [stashapp/CommunityScrapers#966]
Every time I try to use a scraper that uses python i get:
 `Error running scraper script: exec: "python": executable file not found in %PATH%`
Python is installed in it's default location in Windows but it seems I'm missing a setting somewhere. I put the `py_common` folder in \.stash\scrapers but it didn't make a difference.

**Comment by hphpanon** [comment]
Python being installed in its default location is not the same as being accessible in `%PATH%`. If you re-install python there should be an option in the installer to set in the PATH/environment variables. Otherwise, you'll need to manually set it yourself by [modifying Environment Variables](https://www.computerhope.com/issues/ch000549.htm). Depending on your comfort messing around with Windows settings to this degree, I'd suggest going the reinstall approach.

**Comment by seeshepard** [comment]
Thank you it worked. There's an option to add it to PATH in the first page of the installer, but adding via environment variables is easy too.

**Comment by bnkai** [comment]
Closing as the issue was resolved.
